import gimletImg from "../assets/images/gimlet.webp";

export const COCKTAIL = [
  {
    id: 0,
    type: "gin",
    name: "gimlet",
    taste: "balanced",
    prep: "shaken",
    style: "up",
    img: gimletImg,
  },
  {
    id: 1,
    type: "gin",
    name: "martini",
    taste: "boozy",
    prep: "shaken or stirred",
    style: "up",
    img: gimletImg,
  },
  {
    id: 2,
    type: "gin",
    name: "negroni",
    taste: "boozy",
    prep: "stirred",
    style: "rocks",
    img: gimletImg,
  },
  {
    id: 3,
    type: "whiskey",
    name: "old fashioned",
    taste: "boozy",
    prep: "stirred",
    style: "rocks",
    img: gimletImg,
  },
  {
    id: 4,
    type: "whiskey",
    name: "manhatten",
    taste: "boozy",
    prep: "stirred",
    style: "up",
    img: gimletImg,
  },
  {
    id: 5,
    type: "whiskey",
    name: "sour",
    taste: "balanced",
    prep: "shaken",
    style: "up",
    img: gimletImg,
  },
  {
    id: 6,
    type: "tequila",
    name: "margarita",
    taste: "balanced",
    prep: "shaken",
    style: "rocks",
    img: gimletImg,
  },
  {
    id: 7,
    type: "tequila",
    name: "paloma",
    taste: "balanced",
    prep: "shaken",
    style: "rocks",
    img: gimletImg,
  },
  {
    id: 8,
    type: "tequila",
    name: "oaxaca old fashioned",
    taste: "boozy",
    prep: "stirred",
    style: "rocks",
    img: gimletImg,
  },
  {
    id: 9,
    type: "rum",
    name: "daquiri",
    taste: "balanced",
    prep: "shaken",
    style: "up",
    img: gimletImg,
  },
  {
    id: 10,
    type: "rum",
    name: "mojito",
    taste: "balanced",
    prep: "shaken",
    style: "rocks",
    img: gimletImg,
  },
  {
    id: 11,
    type: "rum",
    name: "jungle bird",
    taste: "balanced",
    prep: "shaken",
    style: "rocks",
    img: gimletImg,
  },
];
